### ISSUE TITLE
Problems using the bundle

### ISSUE THREAD

**Issue by merdes** [fervo/FervoDeferredEventBundle#13]
Hey,

I'm trying to use this bundle but i'm having troubles. The event is added to the RabbitMQ Queue correctly but the event listener and the event itself is never executed.

I'm trying in both ways: first letting the listener to do the job and also dispatching manually the deferevent.

Any idea?
Thank you!

### My code:

in my Controller:
```php
$event = new DeferEvent('save.data', new SaveDataEvent($data));
$this->get('event_dispatcher')->dispatch('fervo.defer', $event);
```

`SaveDataEvent.php`

```php
<?php

namespace AppBundle\Event;

use Symfony\Component\EventDispatcher\Event;

class SaveDataEvent extends Event
{
    protected $data;

    public function __construct($data)
    {
        $this->data = $data;
    }

    public function getData()
    {
        return $this->data;
    }

    public function saveData()
    {
        $data = $this->getData();
        // do more stuff
    }
}
```

`SaveDataListener.php`

```php 
<?php

namespace AppBundle\EventListener;

use AppBundle\Event\SaveDataEvent;

class SaveDataListener
{

    /**
     * @var SaveDataEvent
     */
    public function onSendData(SaveDataEvent $event)
    {

        $data = $event->saveData();
    }
}
```

 `services.yml`

```yml
app.save_data_listener:
        class: AppBundle\EventListener\SaveDataListener
        tags:
            -
                name: kernel.event_listener #fervo_deferred_event.listener
                event: send.data
```
